### ISSUE TITLE
Installation error when creating the database

### ISSUE THREAD

**Issue by LucaCinquini** [lukaszlacinski/esgf-auth#2]
(venv) [root@df0efe9a1a13 esgf-auth]# ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/esgf-auth/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/esgf-auth/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/esgf-auth/venv/lib/python2.7/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/esgf-auth/venv/lib/python2.7/site-packages/django/core/management/base.py", line 353, in execute
    self.check()
  File "/usr/local/esgf-auth/venv/lib/python2.7/site-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/esgf-auth/venv/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/usr/local/esgf-auth/venv/lib/python2.7/site-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/esgf-auth/venv/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/esgf-auth/venv/lib/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/esgf-auth/venv/lib/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/esgf-auth/venv/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/esgf-auth/venv/lib/python2.7/site-packages/django/urls/resolvers.py", line 310, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/esgf-auth/venv/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/esgf-auth/venv/lib/python2.7/site-packages/django/urls/resolvers.py", line 303, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/esgf-auth/src/esgf-auth/esgf_auth/urls.py", line 18, in <module>
    from . import views
  File "/usr/local/esgf-auth/src/esgf-auth/esgf_auth/views.py", line 10, in <module>
    from crypto_cookie.auth_tkt import SecureCookie
  File "/usr/local/esgf-auth/venv/lib/python2.7/site-packages/crypto_cookie-0.2.0-py2.7.egg/crypto_cookie/auth_tkt.py", line 11, in <module>
    from paste.auth.auth_tkt import AuthTicket, BadTicket
ImportError: No module named paste.auth.auth_tkt

**Comment by LucaCinquini** [comment]
SOLUTION: pip install paste
(or add "paste" to requirements.txt)

**Comment by lukaszlacinski** [comment]
I am not sure if Paste should be added here as it is not required by esgf-auth. It is required by crypto-cookie and is specified in https://github.com/philipkershaw/crypto-cookie/blob/master/setup.py in extra_require.
However, I added it here to make all prerequisites easier to install.

**Comment by lukaszlacinski** [comment]
I am not sure if Paste should be added here as it is not required by esgf-auth. It is required by crypto-cookie and is specified in https://github.com/philipkershaw/crypto-cookie/blob/master/setup.py in extra_require.
However, I added it here to make all prerequisites easier to install.
